# Generated by Django 6.0.7 on 2026-08-03 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('bed', 'Кровать'), ('sofa', 'Диван'), ('chair', 'Стул'), ('table', 'Стол'), ('wardrobe', 'Шкаф'), ('lamp', 'Лампа')], max_length=30)),
                ('width', models.FloatField(help_text='см')),
                ('height', models.FloatField(help_text='см')),
                ('depth', models.FloatField(help_text='см')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='furniture/')),
            ],
        ),
        migrations.CreateModel(
            name='RoomProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('room_width', models.FloatField()),
                ('room_height', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FurniturePlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('rotation', models.IntegerField(default=0)),
                ('scale', models.FloatField(default=1)),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomplanner.furniture')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='roomplanner.roomproject')),
            ],
        ),
    ]
