# Generated by Django 6.0.6 on 2026-08-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Низький'), ('average', 'Середній'), ('high', 'Високий')], default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Виконати'), ('in_progress', 'В процесі'), ('finish', 'Виконана')], default='todo', max_length=20),
        ),
    ]
